# Generated by Django 4.2.4 on 2024-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('medical_history', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='catshelter/images/')),
            ],
        ),
    ]
