# Generated by Django 4.2.4 on 2024-06-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0003_remove_cat_gender_remove_cat_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
