# Generated by Django 4.2.4 on 2024-06-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0005_image_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=50, unique=True)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_contact', models.CharField(max_length=15)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catshelter.admin')),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
