# Generated by Django 4.2.4 on 2024-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0007_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
