# Generated by Django 4.2.4 on 2024-06-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0010_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images/'),
        ),
    ]
