# Generated by Django 4.2.4 on 2024-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0011_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='cat',
            name='health_condition',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick')], default='Healthy', max_length=50),
        ),
        migrations.AddField(
            model_name='cat',
            name='neuter',
            field=models.BooleanField(default=False),
        ),
    ]
