# Generated by Django 4.2.4 on 2024-07-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0013_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
