# Generated by Django 4.2.4 on 2024-07-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0014_remove_adminlogin_admin_delete_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('stafffullname', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('staffemail', models.CharField(max_length=225)),
                ('staffphone', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='StaffLogin',
            fields=[
                ('username', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=225)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catshelter.staff')),
            ],
        ),
    ]
