# Generated by Django 4.2.4 on 2024-07-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0015_staff_stafflogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafflogin',
            old_name='password',
            new_name='staffpassword',
        ),
        migrations.RenameField(
            model_name='stafflogin',
            old_name='username',
            new_name='staffusername',
        ),
    ]
