# Generated by Django 4.2.4 on 2024-07-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catshelter', '0016_rename_password_stafflogin_staffpassword_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='StaffLogin',
            new_name='AdminLogin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='staffemail',
            new_name='adminemail',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='stafffullname',
            new_name='adminfullname',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='staffphone',
            new_name='adminphone',
        ),
        migrations.RenameField(
            model_name='adminlogin',
            old_name='staff',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='adminlogin',
            old_name='staffpassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminlogin',
            old_name='staffusername',
            new_name='username',
        ),
    ]
