from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("", views.startpage, name="startpage"),
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path('homepage/', views.homepage, name='homepage'),
    path("profile/", views.profile, name="profile"),
    path("editprofile/", views.editprofile, name="editprofile"),
    path('save_profile_changes/', views.save_profile_changes, name='save_profile_changes'),
    path('cats/', views.cat_list, name='cat_list'),
    path('cats/<int:pk>/', views.cat_detail, name='cat_detail'),
    path('cat/add/', views.add_cat, name='add_cat'),
    path('', views.home, name='home'),
    path('about-us/', views.about_us, name='about_us'),
    path('admin/signup/', views.signup_admin, name='admin_signup'),
    path('admin/login/', views.login_admin, name='admin_login'),
    path('admin/dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('admin/catlist/', views.admin_catlist, name='admin_catlist'),
    path('admin/catdetail/<int:cat_id>/', views.admin_catdetail, name='admin_catdetail'),
    path('cats/<int:cat_id>/report/', views.report_cat, name='report_cat'),
    path('cats/<int:cat_id>/submit_report/', views.submit_report, name='submit_report'),
    path('admin/reports/', views.admin_report, name='admin_report'),
    path('cat/<int:cat_id>/update/', views.admin_cat_update, name='admin_cat_update'),
    path('cat/<int:cat_id>/delete/', views.admin_cat_delete, name='admin_cat_delete'),
    path('admin/volunteer/', views.admin_volunteer, name='admin_volunteer'),
    path('volunteer/', views.volunteer_application, name='volunteer_application'),
    path('volunteersubmit/', views.volunteersubmit, name='volunteersubmit'),
    path('verifyvolunteer/', views.verifyvolunteer, name='verifyvolunteer'),
    path('delete_submission/<int:id>/', views.delete_submission, name='delete_submission'),
    path('inventory/', views.inventory_view, name='inventory'),
    path('admin_inventory/', views.admin_inventory_view, name='admin_inventory'),
    path('admin_inventory/add/', views.add_inventory_item, name='add_inventory_item'),
    path('admin_inventory/update/<int:pk>/', views.update_inventory_item, name='update_inventory_item'),
    path('admin_inventory/delete/<int:pk>/', views.delete_inventory_item, name='delete_inventory_item'),
    path('all-users/', views.all_users, name='all_users'),
    path('delete_report/<int:id>/', views.delete_report, name='delete_report'),
    path('admin_fund/', views.admin_fund_view, name='admin_fund'),
    path('add_fund/', views.add_fund, name='add_fund'),
    path('update_fund/<int:pk>/', views.update_fund, name='update_fund'),
    path('delete_fund/<int:pk>/', views.delete_fund, name='delete_fund'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)